### ISSUE TITLE
few questions

### ISSUE THREAD

**Issue by mihaelS** [Akuukis/beancount-interpolate#1]
Hello! 
This is nice plugin, seems that its quite an agile tool.

Please, help me to figure out some cases:

1. How to recur salary exactly two times in a month at a specified dates?  (5 and 20 day every month)

2. How to make accurals every woking day, amount of each accural = FIXED_AMOUNT / NUMBER_WORKING_DAYS_IN_A_MONTH?

Thanks

**Comment by Akuukis** [comment]
Hello, thanks!

For first case, simply add two transactions for 5th and 20th date respectively, and *recur* each of them monthly. You have all the flexibility to name them differently, have different amounts, etc.

Second case is not possible currently. It is planned to add complex PRULEs as in modern calendars (i.e. "every workday" or "every second tuesday") that would make this possible. If you think about spreading salary over only workdays of month, IMO it's fine to include holidays, because resting is very important for productive work :) Otherwise, PR welcome!

Feel free to close this if it answers your questions.
