### ISSUE TITLE
Condition for 

### ISSUE THREAD

**Issue by AS137430** [Akuukis/beancount-interpolate#13]
https://github.com/Akuukis/beancount-interpolate/blob/master/beancount_interpolate/interpolate.py#L85

May I understand why is the second condition for date necessary? to be before current date.
```
while date < begin_date + datetime.timedelta(days=duration) and date <= datetime.date.today():
```
I had to remove it to make my future recurring transactions work and I've checked with Fava the recurring postings are inserted correctly.

**Comment by Akuukis** [comment]
@AS137430 Accounting is about writing down facts, which implies writing down only what's already happened. Therefore I chose to not insert any transaction with a future date. Think of it being automatically inserted *when the day comes*. The expected behavior is that all transactions are including correctly but only up to today, inclusive. Is that working like that for you?

**Comment by AS137430** [comment]
It depends on whether one chooses to use cash basis accounting or accrual basis accounting. IMHO Beancount should be neutral and supports both. I need the future recurring feature so I have gone ahead and modified the code to my needs. Anyway thanks for your clarifications. I'll close the issue then.
