### ISSUE TITLE
Errors importing "beancount_interpolate.recur"

### ISSUE THREAD

**Issue by dofine** [Akuukis/beancount-interpolate#6]
Hi, how to use recur exactly? e.g.  An expense spent every 30 days.
There seems no example. Thanks!

Using examples in readme gives errors as below:

Error importing "beancount_interpolate.recur": dublicate_over_period() takes 3 positional arguments but 4 were given

**Comment by Akuukis** [comment]
Thanks for report, that was a bug. It's fixed now in `v2.1.5`

Currently, `recur` recurs all the `recur`-tagged transactions with the same step, by default every day. To change the default, e.g. to 30 days, use configuration like this:
```
plugin "beancount_interpolate.recur" "{
    'default_step': 'Month',
}"
```

Hopefully that solves the problem for you! Otherwise, please post some examples you are trying to do, and we can think of how to solve it.
